# Generated by Django 4.2.21 on 2025-05-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evento',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
    ]
