# Generated by Django 4.2.21 on 2025-05-26 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_evento_event_rename_usuario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='ciudad',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='titulo',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='event',
            name='destacado',
        ),
        migrations.RemoveField(
            model_name='event',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='event',
            name='enlace_virtual',
        ),
        migrations.RemoveField(
            model_name='event',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tipo',
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Título por defecto', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
