# Generated by Django 4.2.21 on 2025-05-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_event_options_rename_ciudad_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
