# Generated by Django 4.2.21 on 2025-05-26 20:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event_is_active'),
        ('liveEvents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.user'),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora'),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='description',
            field=models.TextField(default='No description available', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='virtual_events/'),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
