# Generated by Django 4.2.21 on 2025-05-26 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtualEvents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualevent',
            options={'ordering': ['-date'], 'verbose_name': 'Evento Virtual', 'verbose_name_plural': 'Eventos Virtuales'},
        ),
        migrations.RemoveField(
            model_name='virtualevent',
            name='time',
        ),
        migrations.AddField(
            model_name='virtualevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='virtualevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='virtualevent',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='virtualevent',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='virtualevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='virtual_events/'),
        ),
        migrations.AlterField(
            model_name='virtualevent',
            name='link',
            field=models.URLField(verbose_name='Enlace de acceso'),
        ),
        migrations.AlterField(
            model_name='virtualevent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
